name: cidex_mobile
description: Warsztat Menager Mobile (WMM) - aplikacja Android korzystająca z CIDEX API
publish_to: "none"
version: 0.4.0+4

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  image_picker: ^1.2.0
  mobile_scanner: ^7.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
